### ISSUE TITLE
No "emod" property

### ISSUE THREAD

**Issue by seanmcilvenna** [rars/ngx-diff#15]
Getting an error about "Type XXX does not have 'emod' property" when running with Angular 13.

**Comment by rars** [comment]
I've tried 0.4.0 with Angular 13 and it seemed to work ok; however, I've just published a [1.0.0](https://www.npmjs.com/package/ngx-diff/v/1.0.0) version of ngx-diff that was built with Angular CLI 13. I've tested this working in the demo app on the [demo](https://github.com/rars/ngx-diff/tree/demo) branch and it looked ok.

Let me know if that fixes your problem. Otherwise a repro or more details on the error would help. Thanks!

**Comment by rars** [comment]
Closing as no response to this issue since my last comment. Please open a new issue if there's still a problem. Thanks.
